// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JobStatus int32

const (
	JobStatus_NONE     JobStatus = 0
	JobStatus_NEW      JobStatus = 1
	JobStatus_STARTED  JobStatus = 2
	JobStatus_PAUSED   JobStatus = 3
	JobStatus_FINISHED JobStatus = 4
)

var JobStatus_name = map[int32]string{
	0: "NONE",
	1: "NEW",
	2: "STARTED",
	3: "PAUSED",
	4: "FINISHED",
}
var JobStatus_value = map[string]int32{
	"NONE":     0,
	"NEW":      1,
	"STARTED":  2,
	"PAUSED":   3,
	"FINISHED": 4,
}

func (x JobStatus) String() string {
	return proto.EnumName(JobStatus_name, int32(x))
}
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_service_3fa2c8546100de88, []int{0}
}

type Error int32

const (
	Error_NIL        Error = 0
	Error_OK         Error = 200
	Error_CREATED    Error = 201
	Error_ACCEPTED   Error = 202
	Error_BADREQUEST Error = 400
	Error_NOTFOUND   Error = 404
)

var Error_name = map[int32]string{
	0:   "NIL",
	200: "OK",
	201: "CREATED",
	202: "ACCEPTED",
	400: "BADREQUEST",
	404: "NOTFOUND",
}
var Error_value = map[string]int32{
	"NIL":        0,
	"OK":         200,
	"CREATED":    201,
	"ACCEPTED":   202,
	"BADREQUEST": 400,
	"NOTFOUND":   404,
}

func (x Error) String() string {
	return proto.EnumName(Error_name, int32(x))
}
func (Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_service_3fa2c8546100de88, []int{1}
}

type Confirmation struct {
	JobID                int32     `protobuf:"varint,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	JobStatus            JobStatus `protobuf:"varint,2,opt,name=jobStatus,proto3,enum=pb.JobStatus" json:"jobStatus,omitempty"`
	Error                Error     `protobuf:"varint,3,opt,name=error,proto3,enum=pb.Error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Confirmation) Reset()         { *m = Confirmation{} }
func (m *Confirmation) String() string { return proto.CompactTextString(m) }
func (*Confirmation) ProtoMessage()    {}
func (*Confirmation) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_3fa2c8546100de88, []int{0}
}
func (m *Confirmation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Confirmation.Unmarshal(m, b)
}
func (m *Confirmation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Confirmation.Marshal(b, m, deterministic)
}
func (dst *Confirmation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Confirmation.Merge(dst, src)
}
func (m *Confirmation) XXX_Size() int {
	return xxx_messageInfo_Confirmation.Size(m)
}
func (m *Confirmation) XXX_DiscardUnknown() {
	xxx_messageInfo_Confirmation.DiscardUnknown(m)
}

var xxx_messageInfo_Confirmation proto.InternalMessageInfo

func (m *Confirmation) GetJobID() int32 {
	if m != nil {
		return m.JobID
	}
	return 0
}

func (m *Confirmation) GetJobStatus() JobStatus {
	if m != nil {
		return m.JobStatus
	}
	return JobStatus_NONE
}

func (m *Confirmation) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NIL
}

type TimeRequest struct {
	JobID                int32    `protobuf:"varint,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeRequest) Reset()         { *m = TimeRequest{} }
func (m *TimeRequest) String() string { return proto.CompactTextString(m) }
func (*TimeRequest) ProtoMessage()    {}
func (*TimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_3fa2c8546100de88, []int{1}
}
func (m *TimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeRequest.Unmarshal(m, b)
}
func (m *TimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeRequest.Marshal(b, m, deterministic)
}
func (dst *TimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeRequest.Merge(dst, src)
}
func (m *TimeRequest) XXX_Size() int {
	return xxx_messageInfo_TimeRequest.Size(m)
}
func (m *TimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TimeRequest proto.InternalMessageInfo

func (m *TimeRequest) GetJobID() int32 {
	if m != nil {
		return m.JobID
	}
	return 0
}

type NewTimeRequest struct {
	New                  bool     `protobuf:"varint,1,opt,name=new,proto3" json:"new,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTimeRequest) Reset()         { *m = NewTimeRequest{} }
func (m *NewTimeRequest) String() string { return proto.CompactTextString(m) }
func (*NewTimeRequest) ProtoMessage()    {}
func (*NewTimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_3fa2c8546100de88, []int{2}
}
func (m *NewTimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTimeRequest.Unmarshal(m, b)
}
func (m *NewTimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTimeRequest.Marshal(b, m, deterministic)
}
func (dst *NewTimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTimeRequest.Merge(dst, src)
}
func (m *NewTimeRequest) XXX_Size() int {
	return xxx_messageInfo_NewTimeRequest.Size(m)
}
func (m *NewTimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewTimeRequest proto.InternalMessageInfo

func (m *NewTimeRequest) GetNew() bool {
	if m != nil {
		return m.New
	}
	return false
}

func init() {
	proto.RegisterType((*Confirmation)(nil), "pb.Confirmation")
	proto.RegisterType((*TimeRequest)(nil), "pb.TimeRequest")
	proto.RegisterType((*NewTimeRequest)(nil), "pb.NewTimeRequest")
	proto.RegisterEnum("pb.JobStatus", JobStatus_name, JobStatus_value)
	proto.RegisterEnum("pb.Error", Error_name, Error_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TimeRecordClient is the client API for TimeRecord service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TimeRecordClient interface {
	// Sends a time request to the server to complete a job request
	CompleteTimer(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*Confirmation, error)
	// Sends a time request to the server to initiate a new job record
	InitiateTimer(ctx context.Context, in *NewTimeRequest, opts ...grpc.CallOption) (*Confirmation, error)
	// Sends a time request to the server to run a timer
	StartTimer(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*Confirmation, error)
	// Sends a time request to the server to update the status to started or paused
	UpdateTimer(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*Confirmation, error)
}

type timeRecordClient struct {
	cc *grpc.ClientConn
}

func NewTimeRecordClient(cc *grpc.ClientConn) TimeRecordClient {
	return &timeRecordClient{cc}
}

func (c *timeRecordClient) CompleteTimer(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*Confirmation, error) {
	out := new(Confirmation)
	err := c.cc.Invoke(ctx, "/pb.TimeRecord/CompleteTimer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeRecordClient) InitiateTimer(ctx context.Context, in *NewTimeRequest, opts ...grpc.CallOption) (*Confirmation, error) {
	out := new(Confirmation)
	err := c.cc.Invoke(ctx, "/pb.TimeRecord/InitiateTimer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeRecordClient) StartTimer(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*Confirmation, error) {
	out := new(Confirmation)
	err := c.cc.Invoke(ctx, "/pb.TimeRecord/StartTimer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeRecordClient) UpdateTimer(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*Confirmation, error) {
	out := new(Confirmation)
	err := c.cc.Invoke(ctx, "/pb.TimeRecord/UpdateTimer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeRecordServer is the server API for TimeRecord service.
type TimeRecordServer interface {
	// Sends a time request to the server to complete a job request
	CompleteTimer(context.Context, *TimeRequest) (*Confirmation, error)
	// Sends a time request to the server to initiate a new job record
	InitiateTimer(context.Context, *NewTimeRequest) (*Confirmation, error)
	// Sends a time request to the server to run a timer
	StartTimer(context.Context, *TimeRequest) (*Confirmation, error)
	// Sends a time request to the server to update the status to started or paused
	UpdateTimer(context.Context, *TimeRequest) (*Confirmation, error)
}

func RegisterTimeRecordServer(s *grpc.Server, srv TimeRecordServer) {
	s.RegisterService(&_TimeRecord_serviceDesc, srv)
}

func _TimeRecord_CompleteTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeRecordServer).CompleteTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TimeRecord/CompleteTimer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeRecordServer).CompleteTimer(ctx, req.(*TimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeRecord_InitiateTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeRecordServer).InitiateTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TimeRecord/InitiateTimer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeRecordServer).InitiateTimer(ctx, req.(*NewTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeRecord_StartTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeRecordServer).StartTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TimeRecord/StartTimer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeRecordServer).StartTimer(ctx, req.(*TimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimeRecord_UpdateTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeRecordServer).UpdateTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TimeRecord/UpdateTimer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeRecordServer).UpdateTimer(ctx, req.(*TimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TimeRecord_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TimeRecord",
	HandlerType: (*TimeRecordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompleteTimer",
			Handler:    _TimeRecord_CompleteTimer_Handler,
		},
		{
			MethodName: "InitiateTimer",
			Handler:    _TimeRecord_InitiateTimer_Handler,
		},
		{
			MethodName: "StartTimer",
			Handler:    _TimeRecord_StartTimer_Handler,
		},
		{
			MethodName: "UpdateTimer",
			Handler:    _TimeRecord_UpdateTimer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_3fa2c8546100de88) }

var fileDescriptor_service_3fa2c8546100de88 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x5d, 0x27, 0x9b, 0x6d, 0x3a, 0x6d, 0x76, 0xad, 0x11, 0x87, 0x8a, 0x0b, 0xab, 0x70, 0xa9,
	0x8a, 0x54, 0x89, 0x82, 0xc4, 0x39, 0x24, 0xae, 0x08, 0xa0, 0xa4, 0x38, 0x09, 0x9c, 0x93, 0xd6,
	0x48, 0xa9, 0x68, 0x1c, 0x5c, 0x97, 0xfe, 0x06, 0x07, 0x3e, 0x0a, 0xf8, 0x0c, 0xbe, 0x04, 0x39,
	0x55, 0xa1, 0x2b, 0xf5, 0xd2, 0x9b, 0xe7, 0xcd, 0x7b, 0x33, 0x6f, 0xc6, 0x03, 0xde, 0x56, 0xa8,
	0x6f, 0xf5, 0x52, 0x4c, 0x5b, 0x25, 0xb5, 0x44, 0xab, 0xad, 0x7c, 0x05, 0xc3, 0x50, 0x36, 0x9f,
	0x6b, 0xb5, 0x29, 0x75, 0x2d, 0x1b, 0x7c, 0x04, 0xce, 0x5a, 0x56, 0x71, 0x34, 0x22, 0xf7, 0x64,
	0xec, 0xf0, 0x43, 0x80, 0xcf, 0xa0, 0xbf, 0x96, 0x55, 0xa6, 0x4b, 0xbd, 0xdb, 0x8e, 0xac, 0x7b,
	0x32, 0xbe, 0x9d, 0x79, 0xd3, 0xb6, 0x9a, 0xbe, 0x3d, 0x82, 0xfc, 0x7f, 0x1e, 0x9f, 0x80, 0x23,
	0x94, 0x92, 0x6a, 0x64, 0x77, 0xc4, 0xbe, 0x21, 0x32, 0x03, 0xf0, 0x03, 0xee, 0x3f, 0x85, 0x41,
	0x5e, 0x6f, 0x04, 0x17, 0x5f, 0x77, 0x62, 0xab, 0xcf, 0xb7, 0xf4, 0x7d, 0xb8, 0x4d, 0xc4, 0xfe,
	0x94, 0x47, 0xc1, 0x6e, 0xc4, 0xbe, 0x63, 0xb9, 0xdc, 0x3c, 0x27, 0x0c, 0xfa, 0xff, 0x1c, 0xa0,
	0x0b, 0xd7, 0x49, 0x9a, 0x30, 0x7a, 0x85, 0x3d, 0xb0, 0x13, 0xf6, 0x89, 0x12, 0x1c, 0x40, 0x2f,
	0xcb, 0x03, 0x9e, 0xb3, 0x88, 0x5a, 0x08, 0x70, 0xb3, 0x08, 0x8a, 0x8c, 0x45, 0xd4, 0xc6, 0x21,
	0xb8, 0xf3, 0x38, 0x89, 0xb3, 0x37, 0x2c, 0xa2, 0xd7, 0x93, 0x8f, 0xe0, 0x74, 0xfe, 0x3a, 0x61,
	0xfc, 0xbe, 0xab, 0x60, 0xa5, 0xef, 0xe8, 0x4f, 0x82, 0x43, 0xe8, 0x85, 0x9c, 0x05, 0xa6, 0xc2,
	0x2f, 0x82, 0x1e, 0xb8, 0x41, 0x18, 0xb2, 0x85, 0x09, 0x7f, 0x13, 0xbc, 0x03, 0x78, 0x1d, 0x44,
	0x9c, 0x7d, 0x28, 0x58, 0x96, 0xd3, 0xef, 0xb6, 0xc9, 0x27, 0x69, 0x3e, 0x4f, 0x8b, 0x24, 0xa2,
	0x3f, 0xec, 0xd9, 0x1f, 0x02, 0x70, 0x18, 0x60, 0x29, 0xd5, 0x0a, 0x5f, 0x82, 0x17, 0xca, 0x4d,
	0xfb, 0x45, 0x68, 0x61, 0x50, 0x85, 0x77, 0x66, 0x33, 0x27, 0x13, 0x3e, 0xa6, 0x06, 0x38, 0xfd,
	0x0e, 0xff, 0x0a, 0x5f, 0x81, 0x17, 0x37, 0xb5, 0xae, 0xcb, 0xa3, 0x0a, 0x0d, 0xe9, 0xe1, 0x6a,
	0xce, 0x0a, 0x9f, 0x03, 0x64, 0xba, 0x54, 0xfa, 0x82, 0x5e, 0x33, 0x18, 0x14, 0xed, 0xaa, 0xbc,
	0xc4, 0x5f, 0x75, 0xd3, 0xdd, 0xd2, 0x8b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xdd, 0x6d,
	0x2a, 0x5c, 0x02, 0x00, 0x00,
}
